### ISSUE TITLE
Политика по отношению к файлам .do

### ISSUE THREAD

**Issue by SerVB** [ischurov/odebook#33]
Вижу, что https://github.com/ischurov/odebook/commit/f658a0a08e7210ee5f8f1da8fdc2b5fa31636938 не применен к аналогичному файлу `.do`. Непонятно: `.do` файлы репозитория больше не поддерживаются? Тогда, может быть, стоит их вообще удалить?

**Comment by ischurov** [comment]
Удалил. Я когда-то давно использовал DocOnce, а потом написал свою систему indentml/qqmbr/qqmathbook и теперь все исходники в `.qq`.

**Comment by SerVB** [comment]
@ischurov, в f44a9652c83931463229174f5525c515aaf5dffb заодно был убит `chapter01.qq`. Этого же не надо было делать?

**Comment by ischurov** [comment]
Да, это я погорячился :) Восстановил (06b36e479d274422341626d9a147aa0040e8f041)
